apiVersion: batch/v1
kind: Job
metadata:
  name: setup
spec:
  template:
    metadata:
      name: setup
    spec:
      containers:
        - name: setup
          image: kbcarter/webapp:2305019
          command: ["/bin/bash","./setup.production.sh"]
          env:
          - name: PASSENGER_APP_ENV
            value: development
      restartPolicy: Never